### ISSUE TITLE
Feature: Assessment reports can be stored into the external OpenSearch component

### ISSUE THREAD

**Issue by 4everming** [vmware-tanzu/cloud-native-security-inspector#25]
**Is your feature request related to a problem? Please describe.**
Make the report can be stored in OpenSearch. And with the data of reports growing, the OpenSearch instances can be deployed and scaled on-demand without data loss. 
By leveraging OpenSearch, it is able to provide flexible APIs to get specific assessment reports and aggregate security data from different dimensions.

**Describe the solution you'd like**
An ES instance should be deployed by a container or OpenSearch Operator before and ready to use.
Users should fill the configurations of OpenSearch into InspectionPolicy including OpenSearch address, username, password, and certificate.
Then the assessment reports can be stored and indexed by OpenSearch.

**Describe the main design/architecture of your solution**

An example of the InspectionPolicy.

```
apiVersion: goharbor.goharbor.io/v1alpha1
kind: InspectionPolicy
metadata:
  name: inspectionpolicy-sample
spec:
 ...
    assessment:
      elasticSearchEnabled: true
      elasticSearchAddr: "https://quickstart-es-http:9200/"
      elasticSearchUser: "elastic"
      elasticSearchPasswd: "2NR422RahwP5NQXG971v74JY"
      elasticSearchCert: |
        -----BEGIN CERTIFICATE-----
        .....
        -----END CERTIFICATE-----
    baselines:
      - kind: "vulnerability"
        baseline: "High"
        version: "v1.1"
        scheme: "application/vnd.security.vulnerability.report; version=1.1"
    actions:
      - kind: "quarantine_vulnerable_workload"
```
